export const  Data=
[
    
       { id:1,data:"The Federal Authority for Identity and Citizenship is tasked with establishing the ‘Population Register and Emirates Identity Card Program’, which includes recording personal and other important data for the entire population in United Arab Emirates and maintaining them in electronic formats. The authority is in charge for issuing the Emirates ID Card to citizens and other persons resident in United Arab Emirates.",
            head:"emirates Id",},
       {id:2,head:"Certificate Attestation",data:"We have different kind of certificate attestation services like standard, premium & high priority depending on the country and customer’s need. Our philosophy of service and integrity make us believe in transparency when assisting our clients, always keeping our clients’ needs in mind. Our team member shines up their knowledge and hence quote you exact time of whole process. We are committed to provide comprehensive Legalization services as per client’s requirements. But enough about us, let’s talk about attestation of your certificates and how we can help you to use it internationally.",},
       {id:3,head:"Famiy Visa",data:"If you have a valid UAE resident visa, you can sponsor first-degree family members to come and live with you in the UAE. After receiving your residence visa, you can begin the procedures for obtaining a spouse and children visa, provided you earn at least 4000 AED per month.You can apply for visas for your family members with Al Wahda Typing Centre. We provide a variety of services related to the issuance, renewal, or cancellation of a dependent visa.",},
       {id:4,head:"Immigration",data:"The Federal Authority for Identity and Citizenship is tasked with establishing the ‘Population Register and Emirates Identity Card Program’, which includes recording personal and other important data for the entire population in United Arab Emirates and maintaining them in electronic formats. The authority is in charge for issuing the Emirates ID Card to citizens and other persons resident in United Arab Emirates.",},
       {id:5,head:"Medical Services",data:"Foreign immigrants seeking to obtain work permits or residence visas in Dubai, need to be certified as medically fit and free of contagious diseases, such as tuberculosis and HIV. To ensure this, foreign nationals must provide proof in the form of medical reports from medical examination centres in Dubai",},
       {id:6,head:"Certificate Attestation",data:"We have different kind of certificate attestation services like standard, premium & high priority depending on the country and customer’s need. Our philosophy of service and integrity make us believe in transparency when assisting our clients, always keeping our clients’ needs in mind. Our team member shines up their knowledge and hence quote you exact time of whole process. We are committed to provide comprehensive Legalization services as per client’s requirements. But enough about us, let’s talk about attestation of your certificates and how we can help you to use it internationally.",},

    
]